"use client"

import { useState } from "react"
import { Activity, ArrowUpRight, BookOpen, Building2, ChevronDown, CircleHelp, Database, FileText, Filter, Globe2, Layers3, Map, Menu, Search, ShieldCheck, SlidersHorizontal, Sparkles, TrendingUp, Users, X } from "lucide-react"

const layers = ["Administrative boundaries", "Land parcels", "Land use / land cover", "Infrastructure projects", "Acquisition & R&R"]
const stats = [{label:"Parcels indexed",value:"18.4M",delta:"+12.6%",icon:Map},{label:"Digitized coverage",value:"68.2%",delta:"+4.8%",icon:Database},{label:"Active acquisition",value:"1,284",delta:"+83 this month",icon:Building2},{label:"Research documents",value:"42.7K",delta:"+1,206",icon:BookOpen}]

export default function Home() {
 const [sidebar,setSidebar]=useState(true); const [active,setActive]=useState("National overview"); const [query,setQuery]=useState(""); const [searched,setSearched]=useState(false); const [role,setRole]=useState("Researcher"); const [activeLayer,setActiveLayer]=useState("Land parcels")
 return <main className="min-h-screen bg-[#081014] text-[#e8f0ef]">
  <header className="flex h-16 items-center justify-between border-b border-[#20343a] bg-[#0b171b] px-5 lg:px-7">
   <div className="flex items-center gap-4"><button className="rounded-lg p-2 hover:bg-[#12242a] lg:hidden" onClick={()=>setSidebar(!sidebar)} aria-label="Toggle menu"><Menu /></button><div className="flex size-9 items-center justify-center rounded-xl bg-[#78e0b5] text-[#081014]"><Globe2 size={20}/></div><div><p className="text-sm font-semibold tracking-wide">NDP RESEARCH</p><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#91a8a9]">National land intelligence</p></div></div>
   <div className="hidden items-center gap-3 md:flex"><span className="font-mono text-[11px] text-[#91a8a9]">SYSTEM STATUS</span><span className="pulse-dot size-2 rounded-full bg-[#78e0b5]"/><span className="text-xs text-[#78e0b5]">All systems operational</span><div className="mx-2 h-6 w-px bg-[#20343a]"/><button className="flex items-center gap-2 rounded-lg border border-[#20343a] px-3 py-2 text-xs hover:bg-[#12242a]"><ShieldCheck size={14} className="text-[#78e0b5]"/> {role}<ChevronDown size={13}/></button></div>
  </header>
  <div className="flex">
   {sidebar && <aside className="fixed inset-y-16 left-0 z-20 w-64 border-r border-[#20343a] bg-[#0b171b] p-4 lg:static lg:min-h-[calc(100vh-4rem)]">
    <div className="mb-6 flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-[.18em] text-[#91a8a9]">Workspace</span><button className="lg:hidden" onClick={()=>setSidebar(false)}><X size={17}/></button></div>
    <nav className="flex flex-col gap-1">{[["National overview",Globe2],["Research repository",BookOpen],["Acquisition monitor",Building2],["Analytics",TrendingUp]].map(([label,Icon])=><button key={label as string} onClick={()=>setActive(label as string)} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm ${active===label?"bg-[#17302f] text-[#78e0b5]":"text-[#91a8a9] hover:bg-[#12242a] hover:text-[#e8f0ef]"}`}><Icon size={17}/>{label as string}</button>)}</nav>
    <div className="mt-8 border-t border-[#20343a] pt-6"><div className="mb-3 flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-[.18em] text-[#91a8a9]">Map layers</span><SlidersHorizontal size={14} className="text-[#91a8a9]"/></div>{layers.map(layer=><button key={layer} onClick={()=>setActiveLayer(layer)} className="flex w-full items-center gap-3 rounded-md px-2 py-2 text-left text-xs text-[#b6c8c7] hover:bg-[#12242a]"><span className={`size-2 rounded-full ${activeLayer===layer?"bg-[#78e0b5]":"border border-[#577276]"}`}/>{layer}</button>)}</div>
    <div className="mt-auto hidden rounded-xl border border-[#20343a] bg-[#0e1a1f] p-3 lg:block"><p className="flex items-center gap-2 text-xs font-medium"><CircleHelp size={14} className="text-[#74b8ff]"/> Prototype environment</p><p className="mt-2 text-[11px] leading-relaxed text-[#91a8a9]">Data is connected to the local FastAPI service with resilient demo fixtures.</p></div>
   </aside>}
   <section className="min-w-0 flex-1 p-4 lg:p-7"><div className="mx-auto max-w-[1500px]">
    <div className="mb-6 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="mb-2 font-mono text-[10px] uppercase tracking-[.22em] text-[#78e0b5]">Research workspace / 12 Sep 2026</p><h1 className="text-2xl font-semibold tracking-tight lg:text-3xl">National overview</h1><p className="mt-2 max-w-xl text-sm text-[#91a8a9]">A living view of land, infrastructure, and policy evidence across the country.</p></div><div className="flex items-center gap-2"><button className="rounded-lg border border-[#20343a] p-2.5 text-[#91a8a9] hover:bg-[#12242a]" aria-label="Filter"><Filter size={17}/></button><button className="flex items-center gap-2 rounded-lg bg-[#78e0b5] px-3 py-2.5 text-xs font-semibold text-[#081014] hover:bg-[#9bf0cb]"><Sparkles size={15}/> Ask the archive</button></div></div>
    <form onSubmit={e=>{e.preventDefault();setSearched(true)}} className="mb-6 flex max-w-3xl items-center gap-3 rounded-xl border border-[#2b4b4f] bg-[#0e1a1f] px-4 py-3 shadow-[0_10px_40px_#0003]"><Search size={18} className="shrink-0 text-[#78e0b5]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ask a question about land, policy, or infrastructure..." className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-[#577276]"/><kbd className="hidden rounded border border-[#20343a] px-2 py-1 font-mono text-[10px] text-[#91a8a9] sm:block">⌘ K</kbd></form>
    <div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{stats.map(({label,value,delta,icon:Icon})=><div key={label} className="rounded-xl border border-[#20343a] bg-[#0e1a1f] p-4"><div className="flex items-start justify-between"><span className="text-xs text-[#91a8a9]">{label}</span><Icon size={16} className="text-[#74b8ff]"/></div><div className="mt-3 flex items-end gap-2"><span className="text-2xl font-semibold tracking-tight">{value}</span><span className="mb-1 font-mono text-[10px] text-[#78e0b5]">{delta}</span></div></div>)}</div>
    <div className="grid gap-4 xl:grid-cols-[1.55fr_1fr]">
     <div className="relative min-h-[480px] overflow-hidden rounded-xl border border-[#20343a] bg-[#102328]"><div className="absolute inset-0 map-grid opacity-80"/><div className="absolute inset-0 opacity-50" style={{background:"radial-gradient(ellipse at 45% 42%, #285e5a 0, transparent 42%), radial-gradient(ellipse at 70% 70%, #1b3e47 0, transparent 38%)"}}/><div className="absolute left-[29%] top-[28%] size-3 rounded-full bg-[#78e0b5] ring-4 ring-[#78e0b533]"/><div className="absolute left-[57%] top-[42%] size-3 rounded-full bg-[#74b8ff] ring-4 ring-[#74b8ff33]"/><div className="absolute left-[69%] top-[65%] size-3 rounded-full bg-[#f1c779] ring-4 ring-[#f1c77933]"/><div className="absolute left-[45%] top-[62%] size-3 rounded-full bg-[#78e0b5] ring-4 ring-[#78e0b533]"/><div className="absolute inset-x-0 top-0 flex items-center justify-between border-b border-[#b8e5d01a] bg-[#0e1a1fcc] px-4 py-3"><div><p className="text-sm font-medium">Live spatial index</p><p className="font-mono text-[10px] text-[#91a8a9]">{activeLayer} / 18,402,771 features</p></div><span className="rounded-md border border-[#31544f] bg-[#17302f] px-2 py-1 font-mono text-[10px] text-[#78e0b5]">LIVE</span></div><div className="absolute bottom-4 left-4 rounded-lg border border-[#b8e5d01a] bg-[#0b171bd9] p-3 backdrop-blur"><p className="mb-2 font-mono text-[10px] uppercase tracking-wider text-[#91a8a9]">Legend</p><div className="flex flex-wrap gap-3 text-[11px] text-[#b6c8c7]"><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-[#78e0b5]"/>Indexed parcel</span><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-[#74b8ff]"/>Infrastructure</span><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-[#f1c779]"/>Acquisition</span></div></div></div>
     <div className="flex flex-col gap-4"><div className="rounded-xl border border-[#20343a] bg-[#0e1a1f] p-5"><div className="mb-5 flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#91a8a9]">Selected feature</p><h2 className="mt-1 text-lg font-medium">Bengaluru Urban Parcel Cluster</h2></div><ArrowUpRight size={17} className="text-[#91a8a9]"/></div><div className="grid grid-cols-2 gap-y-4 text-xs"><div><p className="text-[#91a8a9]">Area indexed</p><p className="mt-1 text-sm font-medium">12,842 acres</p></div><div><p className="text-[#91a8a9]">Reliability</p><p className="mt-1 text-sm font-medium text-[#78e0b5]">94.8%</p></div><div><p className="text-[#91a8a9]">Primary use</p><p className="mt-1 text-sm font-medium">Mixed urban</p></div><div><p className="text-[#91a8a9]">Last updated</p><p className="mt-1 text-sm font-medium">4 hours ago</p></div></div><div className="mt-5 rounded-lg bg-[#12242a] p-3"><p className="flex items-center gap-2 text-xs text-[#b6c8c7]"><Activity size={14} className="text-[#78e0b5]"/> Historical change detected</p><p className="mt-2 text-xs leading-relaxed text-[#91a8a9]">Parcel boundaries reconciled against 2024 satellite imagery. 8.2% land-use transition since 2019.</p></div></div>
      <div className="rounded-xl border border-[#20343a] bg-[#0e1a1f] p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-medium">National digitization</h2><span className="font-mono text-xs text-[#78e0b5]">68.2%</span></div><div className="h-2 overflow-hidden rounded-full bg-[#20343a]"><div className="h-full w-[68%] rounded-full bg-[#78e0b5]"/></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div><p className="text-sm font-medium">26</p><p className="text-[10px] text-[#91a8a9]">States</p></div><div><p className="text-sm font-medium">412</p><p className="text-[10px] text-[#91a8a9]">Districts</p></div><div><p className="text-sm font-medium">9.2M</p><p className="text-[10px] text-[#91a8a9]">Verified</p></div></div></div>
     </div></div>
    {searched && <div className="mt-4 rounded-xl border border-[#31544f] bg-[#0e1a1f] p-5"><div className="flex items-center gap-2 text-sm font-medium"><Sparkles size={16} className="text-[#78e0b5]"/> Archive synthesis</div><p className="mt-3 text-sm leading-relaxed text-[#b6c8c7]">{query?`Based on indexed evidence for “${query}”, the strongest signal is concentrated around urban expansion, acquisition timelines, and inconsistent parcel metadata. Explore the ranked records below.`:"Try asking about land acquisition, watershed change, or digitization progress."}</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>setQuery("Which districts have the highest acquisition risk?")} className="rounded-full border border-[#31544f] px-3 py-1.5 text-xs text-[#78e0b5] hover:bg-[#17302f]">Highest acquisition risk</button><button onClick={()=>setQuery("Show watershed change since 2019")} className="rounded-full border border-[#31544f] px-3 py-1.5 text-xs text-[#78e0b5] hover:bg-[#17302f]">Watershed change</button></div></div>}
   </div></section>
  </div>
 </main>
}
